[package]
name = "testcrate"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "render0"
path = "./src/bin/render0.rs"
required-features = ["alloc"]

[[bin]]
name = "render1"
path = "./src/bin/render1.rs"
required-features = ["alloc"]

# separate feature because we need to test the `ptr_struct` macro both ways and make sure we got configuration correct
[features]
default = ["serde_support", "alloc"]
alloc = ["triple_arena/alloc", "triple_arena_render"]
serde_support = ["triple_arena/serde_support"]

[dependencies]
clap = { workspace = true }
expect-test = { workspace = true }
postcard = { workspace = true }
rand_xoshiro = { workspace = true }
ron = { workspace = true }
stacked_errors = { workspace = true }
star_rng = { workspace = true }
triple_arena = { workspace = true }
triple_arena_render = { workspace = true, optional = true }
