[package]
name = "testcrate"
version = "0.0.0"
edition = "2024"
publish = false

# separate feature because we need to test the `ptr_struct` macro both ways and make sure we got configuration correct
[features]
default = ["serde_support"]
alloc = ["triple_arena/alloc"]
serde_support = ["triple_arena/serde_support"]

[dependencies]
postcard = { version = "1.0", features = ["alloc"] }
rand_xoshiro = "0.8"
serde = "1.0"
serde_derive = "1.0"
stacked_errors = "0.7"
star_rng = { path = "../../star_rng" }
triple_arena = { path = "../triple_arena", features = ["expose_internal_utils"] }
triple_arena_render = { path = "../triple_arena_render" }
